apiVersion: v1
kind: Secret
metadata:
  name: dht-pk
type: Opaque
data: 
  # Peer ID: Qmea94pNZRA9mfSshFN8LnCDdqSvfmjwFo3kReawfkJG4f
  private: Q0FBU3Bna3dnZ1NpQWdFQUFvSUJBUURBVlZLRlFRZ0FFbmRJWkpCTVh5cXEyYlozaDR5Q3RKR0pkcGptc0tuUkoyVWtCRnFGa0FRSVdVeW9QT1h2Lzk4aUlzbkRPU1lYSm5CZXVLbE95S2E2MjFUeHB4cnV4SnNlUEsvcXRXZFpaQ3EyU28vZHpYOTRNUVRVWFFraGlST0tNVmV2RVlKenFISW8razF5c1Btb2ZIMVpiQXBUKy9Ra3JJcWJhbmxXeng3UDlQTFp0Wm56TmlKSDZOVTVIZUxhR1dtRjZGL1JCeUVyVUpDdHd4M3k4dzlJWmpDZFlkc1JXUjMxalNTaDlEUElFWk5rbG9IWjluajRlcitFaUdOOGM2b3lBTlJMdWoxdVdpaUt4am5wR0tvV0krc3RYSEtMQjJCYVllNVU0dmZ4L2RLeGhvTHNVeUxhc3F0QkZmaTcwT3BNWkJ1UloyUnp1eVBPMjFZOUFnTUJBQUVDZ2dFQUtGZjlaa3c4MUY4TFBGa3oxNEZDM3ZHcUQ2cVVNN3FTcUtZQzdxanlCaGhnWTh5eC9FQTRTRlFLKzJOQ3pEUDg1eGtxLzFOV2hSYWdEWTVvblVrRGlFQ0hzZVRlaG1VaE1KZUVReFJvS0YwVmhJVmhaaUk3OGNjK2Z4bEEyQkw3MFVvR1hZZXJ1SDBGN1VpTHhGb1JGR0dBbmFoSEJsVGNZbkQ2NWh6UWRQL0JzOURFMjUyRFI2UVJpSXFrU2czZndHTDBDNzdTSUxFYXhtaWNYRWVPdnViRGE2WWRPQUhHZVM2dGUrTlhyaEJLdFZRaVNIbUFVdllRdjQxU0Q2WWV4Uys3SXNkVFVoS2Q5MkhCMEUveHFFK2xtSzRJSklrdkNKWGtUOEx2M2xxTUZEOTFQR2hFZUM0VEpsK2xYeVRQMnRadm0wVVdaa0JyTytGMGE2a2xOUUtCZ1FEenRlMHMxY3N0U0wxN1p6Z2hXZ1k0MjNWT2dab2tJcmFCN1dZeEd1M3lFbFRZVjRBeUgzQWdQY2puOEk5cFVaRWhCQXFhZExRaVExeVNhWjVTQzRrS0c5a1k0WGJlZlEzRStPU0s0djRnUnpxT2FRcVYxaSt2VWlsS1hkS3BaOWQzcVhkTTJ4MDhnV2dOTW1MVEZnQ1FXWDRPVEM3SG5PYUZLajN2Z3lTdEl3S0JnUURLQ0NtdzBPY0poS2xpRHFESXBCTlVKQ3VjandzMnl0Y0NsUHhuYW1ML2VUTUFGMEFTaHZubFlRaWc4Qm1uakZubGs1ekNJNW90dngydFVnVlpFREFtZFZ1MktKWHA4QUk1cWlXY2JNODdwbisyczBVVWo5RlJGemZ3ckkzSlRsdG1ybmptbzNPT2pVanFlNVhHa3Y0SmI0OEZBekdOeFZZdVZUb1ZoNWVWSHdLQmdIUy9heDMyVVAyaGdmdnl4NFhhblc1eFd6Ry9qanJQVWtUTm1BM2dDNnJTTTBqc0tlSlpBeHErM2xhVisrMkZBSlFqWG56OWVTbU13WFQyR2J6Ti85a1MzQjQ2Sy9xTFI2UmJZd2hSazFHZExhVDVGdlFPaGd0anZabjlkaVJuTldZQ2piOEluR25XeUNUQ1JXcy9lQWV1aDErTUNVRGduZUdmQ2NxS05YQ25Bb0dBVDV1bjBlUi9KV0VBM1lLbUdHbU90RGtNZGtSblJzL21xVDNMdDNSVVRoYVQ0aFZIU2dXbHNwenBxWUR5bXZMUytZT1E0VzdsOGVDODhPN0E3TGRVUWRNOHNDcU42QUNLMys0TG8vZThNT1VLcmhNMXhVUm1WbTJ2dlVaQkdIR24wbTR0ZGJReWRKbDNnZTN3dHE1MUs0S3ArRytwdHhOclFoYVRMS2loTWtFQ2dZQjM0b3hWK3JiMXdmQXduUjR6R2FlOGc5a0ZrR2tOVlc0R3NUOGpNQWJHSGE4SHo1eGFOOU5RcEVlZ0ZML2VLMVoxMHVndTcvYkVuMEFVTHVoSTRjMzNxOENIOXJpOE5oVWl4SXJXUDQyV2hnMTNJQ1J4OExNREYvKzMyTXpEWGtjVy92aDc4RGNxeGxXbUd1K1dEdHlNMWd5S2Z0bVF3Y05OWDVjaDMxN1VSdz09 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dht
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dht
  template:
    metadata:
      labels:
        name: dht
      annotations:  
        prometheus.io/scrape: "true"  
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: dht
          image: gcr.io/prysmaticlabs/chat/dht:latest
          ports:
          - containerPort: 4001
            name: dht
            protocol: TCP
            hostPort: 5000
          - name: metrics
            containerPort: 9090
          args:
            - "--private=$(PRIVATE_KEY)"
          env:
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: dht-pk
                  key: private
---
apiVersion: v1
kind: Service
metadata: 
  name: dht
spec:
  selector:
    name: dht
  type: NodePort
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001
    nodePort: 30100
